version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    networks:
      - ganache-net
    command: ["--networkId", "5777", "--port", "8545", "--hostname", "0.0.0.0", "--deterministic"]

  backend:
    build:
      context: ./smart_contracts
      dockerfile: dockerfile  # Ensure this matches the name of your Dockerfile for smart contracts
    depends_on:
      - ganache
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}  # Optional: Pass environment variables if needed
    networks:
      - ganache-net
    command: ["yarn", "deploy"]  # Adjust this command based on your deployment script
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  frontend:
    build:
      context: ./front-end
      dockerfile: dockerfile  # Ensure this matches the name of your Dockerfile for frontend
    ports:
      - "3003:3000"  # Expose frontend port
    # networks:
    #   - ganache-net
    command: ["yarn", "start"]  # Command to start the frontend application

networks:
  ganache-net:
    driver: bridge
