version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    # command: ["-h", "0.0.0.0", "-a", "10", "-m", "kick aunt absurd media measure velvet note nose prize verb wash essence", "--chainId", "5777"]

  hardhat:
    build:
      context: ./smart_contracts
      dockerfile: dockerfile
    depends_on:
      - ganache
    volumes:
      - ./smart_contracts:/app
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: ["sh", "-c", "while ! nc -z ganache 8545; do sleep 1; done && yarn hardhat run scripts/deploy-vault.js --network ganache"]
  
  frontend:
    build:
      context: ./front-end
      dockerfile: dockerfile
    ports:
      - "3003:3000"
    # depends_on:
    #   - hardhat
    # volumes:
    #   - ./front-end:/app
    # command: ["sh", "-c", "yarn install"]