version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Frontend Docker Image
          command: docker build -t frontend:latest ./front-end
      - run:
          name: Build Backend Docker Image
          command: docker build -t backend:latest ./smart_contracts
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Frontend Image
          command: |
            docker tag frontend:latest $DOCKERHUB_USERNAME/frontend:latest
            docker push $DOCKERHUB_USERNAME/frontend:latest
      - run:
          name: Push Backend Image
          command: |
            docker tag backend:latest $DOCKERHUB_USERNAME/backend:latest
            docker push $DOCKERHUB_USERNAME/backend:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context: dockerhub-context
