version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Use a Python image for Ansible and Docker commands

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker Images
          command: |
            docker build -t $DOCKERHUB_USERNAME/nft-backend ./smart_contracts
            docker build -t $DOCKERHUB_USERNAME/nft-frontend ./front-end
      - run:
          name: Push Docker Images
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/nft-backend
            docker push $DOCKERHUB_USERNAME/nft-frontend
    context:
      - dockerhub-context

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: |
            pip install ansible
      - run:
          name: Deploy to Kubernetes
          command: |
            ansible-playbook -i ansible/inventory ansible/playbooks/deploy.yml
    context:
      - dockerhub-context

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
