version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  build_and_push_docker:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: docker build -t your_dockerhub_username/your_image_name:latest .
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: Push Docker image
          command: docker push your_dockerhub_username/your_image_name:latest

  deploy_to_eks:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Ansible and Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y ansible awscli
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION
      - run:
          name: Run Ansible Playbook
          command: ansible-playbook ansible/deploy.yml -i ansible/hosts

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push_docker
      - deploy_to_eks:
          requires:
            - build_and_push_docker
