version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
          docker_layer_caching: true
      - run:
          name: Debug Environment
          command: |
            echo "DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME"
            echo "DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD"  # Ensure not to print the actual password
            env | grep DOCKERHUB  # Check if the environment variables are set correctly

      - run:
          name: Install Docker Compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Log in to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build and Run Docker Compose
          command: |
            docker-compose -f docker-compose.yml up --build
      - run:
          name: Push Frontend Image
          command: |
            docker tag frontend:latest $DOCKERHUB_USERNAME/frontend:latest
            docker push $DOCKERHUB_USERNAME/frontend:latest
      - run:
          name: Push Backend Image
          command: |
            docker tag backend:latest $DOCKERHUB_USERNAME/backend:latest
            docker push $DOCKERHUB_USERNAME/backend:latest

  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Run Hardhat Tests
          command: |
            cd smart_contracts
            npx hardhat test

  deploy_kubernetes:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Update Package List
          command: sudo apt-get update
      - run:
          name: Install Required Packages
          command: |
            sudo apt-get install -y python3-pip python3-venv
      - run:
          name: Setup Virtual Environment and Install Dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install ansible
            ansible-galaxy collection install kubernetes.core
      - run:
          name: Install Kubectl
          command: |
            curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -o awscliv2.zip
            sudo ./aws/install
      - run:
          name: Configure Kubectl
          command: |
            aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - run:
          name: Deploy to Kubernetes
          command: |
            source venv/bin/activate
            ansible-playbook -i ansible/inventory.yaml ansible/deploy.yaml

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_kubernetes:
          requires:
            - test
