version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Frontend Docker Image
          command: docker build -t frontend:latest ./frontend
      - run:
          name: Build Backend Docker Image
          command: docker build -t backend:latest ./smart_contracts
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_CONTEXT" | docker login --username=_ --password-stdin
          environment:
            DOCKERHUB_CONTEXT: << parameters.contexts.dockerhub-context >>
      - run:
          name: Push Frontend Image
          command: docker tag frontend:latest $DOCKERHUB_REGISTRY/frontend:latest && docker push $DOCKERHUB_REGISTRY/frontend:latest
          environment:
            DOCKERHUB_REGISTRY: docker.io/$DOCKERHUB_USERNAME
      - run:
          name: Push Backend Image
          command: docker tag backend:latest $DOCKERHUB_REGISTRY/backend:latest && docker push $DOCKERHUB_REGISTRY/backend:latest
          environment:
            DOCKERHUB_REGISTRY: docker.io/$DOCKERHUB_USERNAME

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
