version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Use a Python image for Ansible and Docker commands

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker Images
          command: |
            docker build -t $DOCKERHUB_USERNAME/nft-backend ./smart_contracts
            docker build -t $DOCKERHUB_USERNAME/nft-frontend ./front-end
      - run:
          name: Push Docker Images
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/nft-backend
            docker push $DOCKERHUB_USERNAME/nft-frontend

  deploy-to-eks:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Ansible and Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y ansible awscli
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION
      - run:
          name: Run Ansible Playbook
          command: ansible-playbook ansible/deploy.yml -i ansible/hosts

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push-docker
      - deploy-to-eks:
          requires:
            - build-and-push-docker