version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Frontend Docker Image
          command: docker build -t frontend:latest ./front-end
      - run:
          name: Build Backend Docker Image
          command: docker build -t backend:latest ./smart_contracts
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Frontend Image
          command: |
            docker tag frontend:latest $DOCKERHUB_USERNAME/frontend:latest
            docker push $DOCKERHUB_USERNAME/frontend:latest
      - run:
          name: Push Backend Image
          command: |
            docker tag backend:latest $DOCKERHUB_USERNAME/backend:latest
            docker push $DOCKERHUB_USERNAME/backend:latest

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Kubectl
          command: |
            curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -o awscliv2.zip
            sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
      - run:
          name: Configure Kubectl
          command: |
            aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - run:
          name: Install Ansible
          command: sudo apt-get update && sudo apt-get install -y ansible
      - run:
          name: Install Kubernetes Collection
          command: ansible-galaxy collection install kubernetes.core
      - run:
          name: Deploy to Kubernetes
          command: ansible-playbook -i ansible/inventory.yaml ansible/deploy.yaml

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: dockerhub-context
      - deploy:
          requires:
            - build
