# Use the official Node.js 18.16.0 image as a base
FROM node:18.16.0

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies using npm
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 3000 to allow outside access
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
