apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
      - name: ganache
        image: trufflesuite/ganache-cli:latest
        ports:
        - containerPort: 8545
        command: ["--networkId", "5777", "--port", "8545", "--hostname", "0.0.0.0", "--deterministic"]
---
apiVersion: v1
kind: Service
metadata:
  name: ganache
spec:
  selector:
    app: ganache
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545
  type: ClusterIP
