---
- name: Deploy dApp on EKS
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present
      become: true

    - name: Install required Python libraries
      pip:
        name:
          - kubernetes
          - boto3
        state: present

    - name: Ensure AWS CLI is installed
      apt:
        name: awscli
        state: present
      become: true

    - name: Ensure kubectl is installed
      get_url:
        url: https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      become: true

    - name: Configure AWS CLI
      command: |
        aws configure set aws_access_key_id "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws configure set aws_secret_access_key "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        aws configure set region "{{ lookup('env', 'AWS_REGION') }}"

    - name: Update kubeconfig for EKS cluster
      command: aws eks update-kubeconfig --name {{ nftstaking-cluster }}

    - name: Deploy Ganache
      k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: k8s/ganache-deployment.yml

    - name: Deploy Backend
      k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: k8s/backend-deployment.yml

    - name: Deploy Frontend
      k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: k8s/frontend-deployment.yml
