---
- name: Deploy dApp on EKS
  hosts: all
  become: yes
  tasks:
    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install Kubernetes Python library
      pip:
        name: kubernetes
        state: present

    - name: Deploy Ganache
      k8s:
        kubeconfig: kubefile.yml
        state: present
        src: k8s/ganache-deployment.yml

    - name: Deploy Backend
      k8s:
        kubeconfig: kubefile.yml
        state: present
        src: k8s/backend-deployment.yml

    - name: Deploy Frontend
      k8s:
        kubeconfig: kubefile.yml
        state: present
        src: k8s/frontend-deployment.yml
