---
- hosts: all
  become: yes
  tasks:
    - name: Deploy Ganache
      k8s:
        kubeconfig: /path/to/your/kubeconfig
        state: present
        src: k8s/ganache-deployment.yml

    - name: Deploy Backend
      k8s:
        kubeconfig: /path/to/your/kubeconfig
        state: present
        src: k8s/backend-deployment.yml

    - name: Deploy Frontend
      k8s:
        kubeconfig: /path/to/your/kubeconfig
        state: present
        src: k8s/frontend-deployment.yml
