---
- name: Deploy to Kubernetes
  hosts: localhost
  tasks:
    - name: Create frontend deployment
      kubernetes.core.k8s:
        api_version: apps/v1
        kind: Deployment
        metadata:
          name: frontend
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: frontend
          template:
            metadata:
              labels:
                app: frontend
            spec:
              containers:
                - name: frontend
                  image: <your_dockerhub_username>/frontend:latest
                  ports:
                    - containerPort: 3000
