- hosts: localhost
  vars:
    ansible_python_interpreter: "/mnt/d/NFT-Staking-Dapp_Devops/venv/bin/python"
  tasks:
    - name: Deploy Frontend to Kubernetes
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        state: present
        definition: "{{ lookup('file', '../k8s/frontend-deployment.yaml') }}"

    - name: Deploy Backend to Kubernetes
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        state: present
        definition: "{{ lookup('file', '../k8s/backend-deployment.yaml') }}"
