# Use Node.js version 18.16.0 as base image
FROM node:14

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Set environment variables for deployment
ENV SEPOLIA_RPC_URL="https://eth-sepolia.g.alchemy.com/v2/AIjeurCVedrZLU2sSeJSrrsV_sC975tW"

# Command to deploy contracts to Sepolia network
CMD ["npx", "hardhat", "run", "scripts/deploy-vault.js", "--network", "sepolia"]