FROM node:18-alpine3.19

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Compile the contracts
RUN npx hardhat compile

# Set the entry point for the application
CMD ["node", "scripts/deploy-vault.js"]
